### ISSUE TITLE
parseFormData crashes node express server when exceeding max size

### ISSUE THREAD

**Issue by lasseklovstad** [mjackson/remix-the-web#28]
When uploading a file that is too large the `parseFormData` throws an MultipartParseError that is uncatchable. When it is thrown in a Remix action function, Remix is unable to catch it so the server crashes :(

```typescript
const formData = await parseFormData(
    request,
    createTempUploadHandler(),
    { maxFileSize: 20 * 1024 * 1024 },
  );
```

```bash
MultipartParseError: File size exceeds maximum allowed size of 20971520 bytes
    at MultipartParser.#writeBody (file:///C:/projects/pils/node_modules/@mjackson/multipart-parser/dist/lib/multipart.js:240:25)
    at MultipartParser.#write (file:///C:/projects/pils/node_modules/@mjackson/multipart-parser/dist/lib/multipart.js:173:40)
    at MultipartParser.parse (file:///C:/projects/pils/node_modules/@mjackson/multipart-parser/dist/lib/multipart.js:123:28)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
```

**Comment by Bessonov** [comment]
I'm not sure if I encountered the same error. I use `parseMultipartRequest` to retrieve files from Node's request object. When I set `maxFileSize`, I can catch the error and respond with a 422 status. However, after this, the browser's next request to **another** endpoint hangs, although opening a new tab works as expected. There is also a proxy in-between, so not sure it comes from the library.

If I let `maxFileSize` to `Infinity` and stop processing while reading chunks from `file.body`, everything works as expected. It seems like something might not be terminated, closed, or ended properly. However, just by looking at the source code of [multipart.ts](https://github.com/mjackson/remix-the-web/blob/main/packages/multipart-parser/src/lib/multipart.ts), I don't see anything obviously wrong :shrug:

**Comment by mattoni** [comment]
I'm also encountering this issue. 

![image](https://github.com/user-attachments/assets/1f2989ee-674b-4cc7-864a-6af688434e3b)

![image](https://github.com/user-attachments/assets/3d34d02e-99a2-4faa-9f28-735545d1ebfb)

**Comment by mattoni** [comment]
I am only able to prevent my server from crashing by adding 

```
process.on("unhandledRejection", (reason, promise) => {
	logger.error("Unhandled rejection at:", promise, "reason:", reason);
});
```
but that isn't ideal since the error is no longer being handled within the action, so we can't gracefully return a message to the user.

**Comment by Apsysikal** [comment]
I'm having the same issue currently. Couldn't get it to catch the error, no matter where i add the `catch` clause.
Did anyone have any luck in fixing it?

**Comment by sjbuysse** [comment]
Same here, can't figure out a way to catch it

**Comment by lukejagodzinski** [comment]
I've tried to investigate this issue. There is a test for the [parseMultipartRequest](https://github.com/mjackson/remix-the-web/blob/main/packages/multipart-parser/src/lib/multipart.test.ts#L246) function that is being used inside `parseFormData`. However, it's testing a case where developer didn't provide uploadHandler, meaning that the default one is being used which doesn't stream but reads the whole body into memory at once:

```ts
async function defaultFileUploadHandler(file) {
  let buffer = await file.arrayBuffer();
  return new File([buffer], file.name, { type: file.type, lastModified: file.lastModified });
}
```

And in deed, when I didn't provide uploadHandler the function doesn't kill the server. I've tried to pinpoint the exact place where the problem happens and I think it's the incorrect handling of the error in the [parseMultipart](https://github.com/mjackson/remix-the-web/blob/main/packages/multipart-parser/src/lib/multipart.ts#L64-L102) function.

When error happens it doesn't get to the line where it should actually throw error:
```
  if (parseError) {
    throw parseError;
  }
```
It's stuck in the while loop? I couldn't determine that. I have a hunch that error should be throw earlier. But I would have to better understand the code.

**Comment by mjackson** [comment]
The conversion of the promise-based `parser.parse(message)` API to the `AsyncGenerator` return value you get from `parseMultipart` is tricky to get right, and I think I'd like to remove it in the next minor and simplify the code.

For now, you can work around this issue by using the low-level promise-based API, but you'll have to parse out the boundary yourself.

```ts
import { getMultipartBoundary, MultipartParser } from '@mjackson/multipart-parser';

let boundary = getMultipartBoundary(request.headers.get('Content-Type'));
let parser = new MultipartParser(boundary);

try {
  await parser.parse(request.body, (part) => {
    // handle each part
  });
} catch (error) {
  console.error(error);
}
```

This doesn't help if you're using `parseFormData`, but it should help if you're using the lower-level multipart parser directly. I'll have an update within a few days.

**Comment by mjackson** [comment]
Sorry, closed prematurely. `multipart-parser` is fixed in 0.8, but I still need to update form-data-parser.

**Comment by mjackson** [comment]
The fix was released in [form-data-parser v0.7](https://github.com/mjackson/remix-the-web/releases/tag/form-data-parser%400.7.0)

**Comment by mjackson** [comment]
Oh! I forgot to mention that I made you all [a little demo that shows you how to use this feature](https://github.com/mjackson/remix-the-web/tree/main/packages/form-data-parser/examples/node). I've tested everything locally with Node 23.6.0. Please give it a shot and LMK how it goes!

**Comment by lukejagodzinski** [comment]
@mjackson thanks! but can't update the package. I get the following error:

```
npm add @mjackson/form-data-parser@latest

npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:^
```

**Comment by mjackson** [comment]
Oof, thanks for the heads up @lukejagodzinski. My publish script failed on the JSR publish step so I had to publish manually from my laptop and it looks like I screwed it up.

It should be fixed in 0.8.1

See https://www.unpkg.com/@mjackson/multipart-parser@0.8.1/package.json

Sorry about the bad publish!

**Comment by lukejagodzinski** [comment]
@mjackson thanks! Now it works :)

**Comment by sjbuysse** [comment]
Am I doing something wrong? Still crashes for me. using form-data-parser 0.7 and multipart-parser 0.8.2
```
export const uploadImagesAndUpdateFormdata = async (request: Request) => {
  async function uploadHandler(fileUpload: FileUpload) {
    // Is this file upload from the <input type="file" name="imageFiles"> field?
    if (fileUpload.fieldName === "imageFiles") {
      // if there is no file attached to the formControl, return null
      if (!fileUpload.name) {
        return null;
      }
      const uploadedImage = await uploadImage(fileUpload.stream());
      return uploadedImage.public_id;
    }
    // Ignore any files we don't recognize the name of...
  }

  try {
    const formData = await parseFormData(
      request,
      {
        maxFileSize: 3000000,
      },
      uploadHandler
    );

    return formData;
  } catch (error) {
    if (error instanceof MaxFileSizeExceededError) {
      return Response.json(error.message, { status: 413 });
    }

    if (error instanceof MultipartParseError) {
      return Response.json(error.message, { status: 400 });
    }

    return Response.json("Internal Server Error", { status: 500 });
  }
};
```

**Comment by lukejagodzinski** [comment]
The error you get is the correct one, so the issue is probably not in this function but somewhere outside of it and how you handle/consume it.
